### ISSUE TITLE
A Mongo option for FileMan (File) RPCs

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/VICSServer#3]
This issue is a carry-over from a nonClinicalRPC research issue; we'll close out the research issue in favor of this prototyping/implementation issue. However, we'll retain all the important, relevant notes here.

## Objective
We want a way to Emulate RPCs using MongoDB as a data store instead of VISTA Fileman. This isn't as straightforward as it sounds though, since we'll need to ensure we have the right constraints on the MongoDB data model (as it relates to the MVDM), and we also need to address the asynchronous nature of most all MongoDB data accesses (currently, we handle data accesses in RPC emulation using a synchronous execution model). To this end, we'll need to:

* [x] Implement a low-level data service that provides access to an underlying MongoDB service and ensures data schema integrity and compatibility with MVDM models (Issue #5)
* [x] Implement a higher-level data access/search service that allows RPC emulation code to pull MVDM-like data hosted on MongoDB
* [x] Scope the meta (non-clinical) RPCs from select clinical domain captures that we can target for MongoDB conversion (allergies, vitals, problems). (Issue #6)
* [ ] Prototype an instrumented dispatcher that will process RPCs using an asynchronous execution model, work it into the RPC Server (this might require reworking the underlying RPC Server architecture) **We can say that the asynchronous dispatcher will handle all the pure JS emulations.** (Issue #3)
* [x] Implement the emulations for the RPCs scoped out in the previous step
* [x] Compare benchmark numbers between native (RPC Broker via socket) vs. passthru (VISTA MUMPS via GT.M) vs. Emulation (over MongoDB)

We'll set up additional issues to track these tasks, but the order should be something like:
1. Scope the appropriate RPCs, determine data types needed, pull data into MongoDB
2. Create low-level data service
3. Create higher-level data service for lexicon-type search
4. Implement new dispatcher
5. Implement RPCs

## Notes

Moving this from [nonClinicalRPCs issue #55](https://github.com/vistadataproject/nonClinicalRPCs/issues/55)

Assigning to Mike to consider design. Background task as we get into the File RPCs.

__Goal__: can configure ncRPC locker for File access to work over Mongo instead of FileMan. This will show how to migrate a large chunk of VISTA interactions into ___a centralized, modern, pure JS configuration__.

__Background:__

there are six ways to implement RPCs
  1. pure Javascript
  2. __M(VDM) over FileMan__
  3. over Javascript API (ex/ Parameter RPCs)
  4. __M(VDM) over Mongo__
  5. traditional all MUMPS
  6. traditional MUMPS/FileMan.

We want to show both [2] File RPCs being locked over VDM/FileMan AND [4] the same RPCs being locked over Mongo.

But we do NOT want two RPC locker implementations. Instead we want the RPC locker to be passed a facade that will resolve the same DESCRIBE/SELECT calls over Mongo or VDM/FileMan.

__Work Order__: 
  * first File RPC locking DIRECTLY over VDM (no consideration of Mongo)
     * clone data will have to be imported into FileMan/VDM from its Mongo cache
  * once working, consider Facade design to allow resolution over Mongo.
  * facade can direct to VDM/FileMan or Mongo option
  * the management client will be updated to allow switching between Mongo and traditional VISTA and clearly show Mongo-backed calls (Javascript-only calls). Note that utility RPCs (calculation only RPCs) will have already been show cased in the Management Client so this further set of RPCs will be adding to that "JS-only" demonstration.
  * note that we can re-house Parameter data the same way later with the Parameter API working over both VISTA's parameter i/f and a Mongo JS equivalent

## Brainstorming Notes
One hurdle we'll have to overcome here is the fact that all of the (M)VDM calls use a synchronous execution model, whereas the JS driver code for MongoDB is asynchronous. I have some ideas I'm working out though.  Experimenting with ES6 generators

## VDP Architecture Notes

Here's some of my thoughts after investigating the VDP code a little bit more, doing some experimenting with various solutions, and brainstorming objectives, goals, and issues:

### Goals
* We want to have a generic data service to allow save/retrieve to/from an external data source, not tied to a specific implementation
    * API to abstract away specific implementation
    * Centralized access to data
    * Projections (a la MongoDB to reduce bandwidth usage)
* We also want to be able to wrap a facade/router around multiple data sources, and route requests based on content, access rules, etc
    * Transparently support multiple data sources/protocols
        * GT.M VistA 
        * Cache VistA
        * Mongo DB
        * REST/Web Service
    * API/toolkit useful to (M)VDM/Locker

### Issues
* JS execution path mechanisms for all wrapped data sources need to be homogeneous (either *all* synchronous or *all* asynchronous. (Leaning toward asynchronous instead of synchronous with workarounds (like queues, etc), which is matches the spirit of JS/NodeJS and fits into patterns most JS developers are familiar with)
* In VDP, low-level data access mechanism for GT.M VistA (nodem) is strictly synchronous
* Asynchronous execution model introduces issues with concurrent access to globals via multiple execution paths.
* Multiple utilities used by the (M)VDM are written using a synchronous execution approach (no callbacks, throwing error conditions)

### Mitigations via Architecture Considerations
* The biggie: VDP goes **ASYNCHRONOUS**. We would need to come up with a way to mitigate the concurrent global access in VistA inherent in an asynchronous execution model. But I think this is worth pursuing. Instead of building around VistA/nodem quirks, I think we should consider going the opposite way: tweak the rules interfaces to VistA and nodem to fit the 'normal' JS/Node asynchronous execution model, which is industry standard.
* Wrap the nodem driver with a simple asynchronous shim
    * Pretty easy to do
    * Not truly asynchronous, but we can at least make the execution mechanism seem asynchronous
    * We can get close by deferring the nodem synchronous execution to the back of the call stack
    * This is not a problem with the Cache NodeJS interface, since its driver supports asynchronous execution paths.  It's only nodem that's uniquely synchronous.
* Create a lower level module (Data Model or DM) which exposes data store methods via a standard API: VDP stack becomes: **DM => VDM => MVDM**
    * The (M)VDM would sit on the DM, and would encapsulate the data access functionality inherent to a particular system (e.g. GT.M VistA, Cache VISTA, MongoDB). Functional decomp of the DM boils down to 3 sub-categories:
        * Fileman FILE CRUD
        * Paramter CRUD
        * 'Function' interface
    * All API functions should be asynchronous in nature, and model a standard data access API
    * Currently, functional composition made up of the existing collection low-level utilities
        * nodem
        * fileman
        * fmql
        * Parameter Service
        * dmUtils
        * even some vdmUtils
    * Get rid of all references to the nodem "db" driver object in (M)VDM/Locker/Dispatcher code; the point of the DM is to completely abstract away the system-specific interfaces - like nodem - from the higher level code base. Instead of using the existing nodem driver, (M)VDM/Util/Locker/Dispatcher code would use the DM object interface to access the underlying data store.
    * DM would be a singleton, keeping initialization/resource management clean, isolated and organized.
    * DM object built via factory at runtime, possible create DM facade composed of multiple DM implementations with routing logic built in.

### Potential Risks
* Large-ish VDP codebase to retool
* API considerations
    * Do we cover all the utility bases?
    * How do we cover one-off function execution and/or expose custom lower level utility functionality to higher level functions that need it (e.g. RPC Runner)

## Before Mongo - try async version of Utility RPCs

Utility RPCs are pure JS. Right now, server still sends them to a worker. However, server could handle these RPCs asynchronously in the RPC Server, in the "normal" one-thread node way.

To try:
- handle one of these RPCs asynchronously (ORWU DT?)
- compare server performance for the async version to the current worker version
 ### Async JS Utility RPCs
(Note: I've isolated the work captured for this issue into a [single feature branch](https://github.com/vistadataproject/nodeVISTA/tree/dev-server-base/async-emulator) in the **nodeVISTA** repo. This branch was created for experimental purposes only and **SHOULD NOT** be merged into the production **master** branch!)

To test the feasibility of an asynchronous execution model for emulators, I created a one-off *asynchronous* emulator, then wrapped the JS Utility emulation model invocation functions with functions that had asynchronous call signatures. I tested two wrapping techniques:

* **Deferred**: The invocation function is deferred to the back of the JS call stack, more closely simulating an asynchronous execution model.
* **Inline**: The invocation function is performed inline with the execution call. The wrapper function only provides an "asynchronous-looking" facade, but is really calling the invocation function synchronously.

Three test runs were done with the feature branch using CPRS as a test client and timed using the NodeJS `process.hrtime()` utility:
* Standard emulator/process queue
* Async emulator - deferred invocation
* Async emulator - inline invocation

### Test Results/Timing
[Timing numbers can be accessed here](https://github.com/vistadataproject/nodeVISTA/blob/dev-server-base/async-emulator/rpcServer/timingCounts.txt), but the results are not all that surprising. The standard emulator RPC handling over process queue was at least an order of magnitude slower than either of the async emulator test cases. This was most likely due to the overhead incurred by the IPC barrier that the request/response data needs to flow through with the queueing scheme. Also not surprisingly, the inline execution is slightly faster than the deferred execution.

We could implement something similar, but to have a unified facade (via the dispatcher) we'd need to modify the execution models of the rest of the emulators. But, this feature branch proves that we can, in fact, do it if we wanted to.

### "Asynchronous" Nodem?
One interesting thought that came out of the analysis work is how easy it would be to create an "asynchronous" API for the nodem GT.M driver utility. Unlike the Cache version of the driver, the nodem library does **not** support asynchronous activities. However, we could use the same "deferred wrapping" on the nodem API functions. This would not only give us an asynchronous execution model at the lowest level (to prep for Mongo equivalency) but would also give us a slightly better error handling mechanism (we could return errors via callback `error` parameter)
