### ISSUE TITLE
Spike: Research REST API documentation tools/platforms

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/VICSServer#309]
This is a sidebar to the related issue listed in [VAM Jira](https://hawaiirg.atlassian.net/browse/VAM-652). We'll use this Github issue to record notes, have team discussions, etc. outside of what gets reported in Jira. Including @creindle and @kekuso here so that they (hopefully) get notified for changes.

## Background
We'll want to use a tool/platform that will allow us to create HTTP specs which will allow us to auto-generate documentation for the VICS Server HTTP APIs we develop. The tool/platform needs to be:

- Non-intrusive (minimal external files to manage)
- Easy to use for auto-generation of documentation
- Widely used by industry (subjective)
- Open source (i.e. free as in beer/speech)

Some examples of tools/platforms are

- OpenAPI/Swagger
- API Blueprint
- RAML

## Tasks
To call this task complete, we should
- [ ] Do a thorough investigation of multiple tools/platforms
- [ ] Come up with a list of pros/cons for the various tools/platforms and a preferred platform
- [ ] Code a mini demonstration of the tool/platform of choice. The demo should:
- [ ] Show a sample of the additional code/files needed to document an API
- [ ] Sample generation of documentation created by/from the tool/platform

From this, we'll discuss as a group to determine documentation direction.
